### ISSUE TITLE
HTTPConnectionPool(host='qb', port=4861): Max retries exceeded with url: /api/1.0/quizbowl/status

### ISSUE THREAD

**Issue by darthnithin** [Pinafore/qanta-codalab#10]
I installed everything following instructions however when i run `docker-compose up`. I get the following error:
```
PS C:\Users\*****\qanta-codalab> docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`

Starting qanta-codalab_qb_1 ... done
Starting qanta-codalab_eval_1 ... done
Attaching to qanta-codalab_qb_1, qanta-codalab_eval_1
qb_1    | INFO: Using base environemnt
eval_1  | /eval/evaluate.py:75: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
eval_1  |   elog.warn(e)
eval_1  | HTTPConnectionPool(host='qb', port=4861): Max retries exceeded with url: /api/1.0/quizbowl/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2e95a6f60>: Failed to establish a new connection: [Errno 111] Connection refused'))
eval_1  | HTTPConnectionPool(host='qb', port=4861): Max retries exceeded with url: /api/1.0/quizbowl/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2dc12dba8>: Failed to establish a new connection: [Errno 111] Connection refused'))
eval_1  | HTTPConnectionPool(host='qb', port=4861): Max retries exceeded with url: /api/1.0/quizbowl/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2dbcbf2e8>: Failed to establish a new connection: [Errno 111] Connection refused'))
eval_1  | HTTPConnectionPool(host='qb', port=4861): Max retries exceeded with url: /api/1.0/quizbowl/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2dbcbf9e8>: Failed to establish a new connection: [Errno 111] Connection refused'))
...
eval_1  | Failed to find a running web server beep boop, prepare for RUD
eval_1  | Traceback (most recent call last):
eval_1  |   File "/eval/evaluate.py", line 259, in <module>
eval_1  |     evaluate()
eval_1  |   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 722, in __call__
eval_1  |     return self.main(*args, **kwargs)
eval_1  |   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 697, in main
eval_1  |     rv = self.invoke(ctx)
eval_1  |   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 895, in invoke
eval_1  |     return ctx.invoke(self.callback, **ctx.params)
eval_1  |   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 535, in invoke
eval_1  |     return callback(*args, **kwargs)
eval_1  |   File "/eval/evaluate.py", line 193, in evaluate
eval_1  |     raise ValueError('Status API could not be reached')
eval_1  | ValueError: Status API could not be reached
qanta-codalab_eval_1 exited with code 1
qb_1    |  * Serving Flask app "tfidf" (lazy loading)
qb_1    |  * Environment: production
qb_1    |    WARNING: Do not use the development server in a production environment.
qb_1    |    Use a production WSGI server instead.
qb_1    |  * Debug mode: off
qb_1    | /opt/conda/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
qb_1    |   from collections import Mapping, defaultdict
qb_1    |  * Running on http://0.0.0.0:4861/ (Press CTRL+C to quit)
```
This keeps going. I am unable to find the cause of this

**Comment by darthnithin** [comment]
So it seems like this error can be ignored. Also dont do `http POST http://0.0.0.0:4861/api/1.0/quizbowl/act` do `http POST http://127.0.0.1:4861/api/1.0/quizbowl/act` per <https://httpie.io/docs#url-shortcuts-for-localhost>
