### ISSUE TITLE
Wrong data files?

### ISSUE THREAD

**Issue by ezubaric** [Pinafore/qanta-codalab#7]
Starting from a clean install, I grab the data (download) task and then start the webserver (docker-compose up):
`eval_1  | Traceback (most recent call last):
eval_1  |   File "/eval/evaluate.py", line 229, in <module>
eval_1  |     evaluate()
eval_1  |   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 722, in __call__
eval_1  |     return self.main(*args, **kwargs)
eval_1  |   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 697, in main
eval_1  |     rv = self.invoke(ctx)
eval_1  |   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 895, in invoke
eval_1  |     return ctx.invoke(self.callback, **ctx.params)
eval_1  |   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 535, in invoke
eval_1  |     return callback(*args, **kwargs)
eval_1  |   File "/eval/evaluate.py", line 177, in evaluate
eval_1  |     with open(input_dir) as f:
eval_1  | FileNotFoundError: [Errno 2] No such file or directory: 'data/qanta.dev.paragraphs.2018.04.18.json'`

Is there an intermediate step that's missing, or is the wrong file listed?

Download grabs:
`$ ls data/
qanta.dev.2018.04.18.json	qanta.test.2018.04.18.json
qanta.mapped.2018.04.18.json	qanta.train.2018.04.18.json`

**Comment by EntilZha** [comment]
I think this is a result of Ahmed/Chen changing the code to accommodate paragraphs, and not testing their code. I am going to revert any changes that reference that file until I see a PR that very clearly shows that testing was done to make sure it works correctly.

**Comment by EntilZha** [comment]
I changed the incorrect reference here: 
https://github.com/Pinafore/qanta-codalab/blob/master/docker-compose.yml#L24

I believe that should fix it
